### ISSUE TITLE
Minor optimizations and standards adoption

### ISSUE THREAD

**Issue by Goro2030** [juancri/pasoapaso#1]
First of all, excellent initiative and very useful community service!

When looking at the Dev. Tools, I've found the following possible optimizations to the code:

Accessibility
```
<li> elements must be contained in a <ul> or <ol>: List item does not have a <ul>, <ol> parent element without a role, or a role="list"
ARIA input fields must have an accessible name: Element has no title attribute
Images must have alternate text: Element has no title attribute
Links must have discernible text: Element has no title attribute
Required ARIA attributes must be provided: Required ARIA attribute not present: aria-expanded
```
Compatibility
`The 'x-ua-compatible' meta element should not be specified as it is not needed.`

**Comment by juancri** [comment]
Hi, Goro2030

I guess  you found these issues with https://www.puedoir.cl/

We are not using `<ul>` or `<li>` anymore.

About the warning about 'x-ua-compatible', I'll take a look but it does not seem to be an important issue.

Thank you for the report!

**Comment by Goro2030** [comment]
Yes, I was referring to puedoir.cl . 

I've checked and the <ul> and <li> warnings do not show anymore , but now there are many more warning, and some errors now!

Errors:

Security
```
Response should include 'x-content-type-options' header.
REQUESThttps://www.puedoir.cl/back.svg
```

Performance
```
A 'cache-control' header is missing or empty.
REQUESThttps://www.puedoir.cl/back.svg
```

**Comment by juancri** [comment]
Those are handled by the CDN, so I wouldn't worry much. Also, the website is static and it doesn't handle any sensitive information so there are no big security concerns.
